# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.box_version = "1804.02"

  config.vm.provision "shell", path: "provision.sh"
end
