# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :inetRouter => {
        :net => [
            { ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net" },
        ]
    },
    :centralRouter => {
        :net => [
            { ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net" },
            { ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net" },
            { ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net" },
            { ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net" },
        ]
    },
    :centralServer => {
        :net => [
            { ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net" },
        ]
    },
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = "centos/7"
            box.vm.host_name = boxname.to_s

            boxconfig[:net].each do |ipconf|
                box.vm.network "private_network", ipconf
            end

            case boxname.to_s
                when "inetRouter"
                    box.vm.provision "shell", inline: <<-SHELL
                        echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.conf
                        sysctl -p /etc/sysctl.conf

                        nmcli connection modify System\ eth1 ipv4.routes "192.168.0.0/16 192.168.255.2"
                        nmcli connection up System\ eth1

                        # sysctl net.ipv4.conf.all.forwarding=1
                        # iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
                    SHELL
                when "centralRouter"
                    box.vm.provision "shell", inline: <<-SHELL
                        echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.conf
                        sysctl -p /etc/sysctl.conf

                        # sysctl net.ipv4.conf.all.forwarding=1
                        # echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
                        # echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
                        # systemctl restart network
                    SHELL
                when "centralServer"
                    box.vm.provision "shell", inline: <<-SHELL
                        echo 111111 | passwd --stdin vagrant
                        sed -i '/PasswordAuthentication no/d' /etc/ssh/sshd_config
                        systemctl restart sshd

                        nmcli connection modify System\ eth1 ipv4.dns 8.8.8.8 ipv4.gateway 192.168.0.1
                        nmcli connection up System\ eth1

                        # echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
                        # echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
                        # systemctl restart network
                    SHELL
            end
        end
    end
end

