# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
  end

  config.vm.define "node1" do |node1|
    node1.vm.hostname = "node1.local"
    node1.vm.network "private_network", ip: "10.0.10.2"
  end

  config.vm.define "node2" do |node2|
    node2.vm.hostname = "node2.local"
    node2.vm.network "private_network", ip: "10.0.10.2"
  end

  config.vm.define "node3" do |node3|
    node3.vm.hostname = "node3.local"
    node3.vm.network "private_network", ip: "10.0.10.2"
  end
end
