# -*- mode: ruby -*-
# vim: set ft=ruby :
disks_dir = '/mnt/hd/vm-disks/'

MACHINES = {
    :hw3 => {
        :box_name => "centos/7",
        :box_version => "1804.02",
        :disks => {
            :sata1 => {
                :dfile => disks_dir + 'sata1.vdi',
                :size => 10240,
                :port => 1
            },
            :sata2 => {
                :dfile => disks_dir + 'sata2.vdi',
                :size => 2048,
                :port => 2
            },
            :sata3 => {
                :dfile => disks_dir + 'sata3.vdi',
                :size => 1024,
                :port => 3
            },
            :sata4 => {
                :dfile => disks_dir + 'sata4.vdi',
                :size => 1024,
                :port => 4
            }
        }
    }
}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|

        config.vm.define boxname do |box|

            box.vm.box = boxconfig[:box_name]
            box.vm.box_version = boxconfig[:box_version]

            box.vm.host_name = boxname.to_s

            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "200"]
                needsController = false
                boxconfig[:disks].each do |dname, dconf|
                    unless File.exist?(dconf[:dfile])
                        vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                        needsController =  true
                    end

                end
                if needsController == true
                    vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                    boxconfig[:disks].each do |dname, dconf|
                        vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                    end
                end
            end

            box.vm.provision "shell", inline: <<-SHELL
                yum install -y xfsdump vim
            SHELL
        end
    end
end
