# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.hostname = "server"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
  end
end
